# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-20 12:39
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0009_remove_entity_visibility'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedEntity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='entities.Entity')),
            ],
        ),
        migrations.CreateModel(
            name='CachedEntityTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='repocache.CachedEntity')),
            ],
        ),
        migrations.CreateModel(
            name='CachedEntityVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('restricted', 'Restricted'), ('public', 'Public')], help_text='Public = anyone can view<br />Restricted = logged in users can view<br />Private = only you can view', max_length=16)),
                ('sha', models.CharField(max_length=40)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='repocache.CachedEntity')),
            ],
        ),
        migrations.AddField(
            model_name='cachedentitytag',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='repocache.CachedEntityVersion'),
        ),
        migrations.AddField(
            model_name='cachedentity',
            name='latest_version',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='repocache.CachedEntityVersion', null=True),
        ),
        migrations.AlterUniqueTogether(
            name='cachedentityversion',
            unique_together=set([('entity', 'sha')]),
        ),
        migrations.AlterUniqueTogether(
            name='cachedentitytag',
            unique_together=set([('entity', 'tag')]),
        ),
    ]
