# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-01 10:22
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('repocache', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedentityversion',
            name='timestamp',
            field=models.DateTimeField(default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
