# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-10-15 16:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repocache', '0003_auto_20181012_1337'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedentitytag',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='repocache.CachedEntityVersion'),
        ),
    ]
