# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-16 14:33
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repocache', '0004_auto_20181015_1620'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cachedentityversion',
            options={'get_latest_by': 'timestamp', 'ordering': ['-timestamp']},
        ),
    ]
