# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-12-13 13:01
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repocache', '0005_auto_20181116_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedentityversion',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public')], help_text='Public = anyone can view<br />Private = only you can view', max_length=16),
        ),
    ]
