# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-11 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repocache', '0006_auto_20181213_1301'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolInterface',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('term', models.CharField(blank=True, help_text='an ontology term in the interface', max_length=500)),
                ('optional', models.BooleanField(help_text='whether this term is required to be present in models')),
                ('protocol_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interface', to='repocache.CachedEntityVersion')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='protocolinterface',
            unique_together=set([('protocol_version', 'term')]),
        ),
    ]
