# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-02-18 15:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repocache', '0007_auto_20190111_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='cachedentityversion',
            options={'get_latest_by': 'timestamp', 'ordering': ['-timestamp', '-pk']},
        ),
    ]
