# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-07-03 15:53
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repocache', '0009_auto_20190408_1205'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedentityversion',
            name='parsed_ok',
            field=models.BooleanField(default=False, help_text='Whether this entity version has been verified as syntactically correct'),
        ),
    ]
