# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-20 14:57
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repocache', '0012_split_cache'),
    ]

    operations = [
        migrations.AlterField(
            model_name='protocolinterface',
            name='new_protocol_version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='interface', to='repocache.CachedProtocolVersion'),
        ),
        migrations.AlterUniqueTogether(
            name='protocolinterface',
            unique_together=set([('new_protocol_version', 'term')]),
        ),
        migrations.RemoveField(
            model_name='protocolinterface',
            name='protocol_version',
        ),
        migrations.RenameField(
            model_name='protocolinterface',
            old_name='new_protocol_version',
            new_name='protocol_version',
        ),
        migrations.AlterUniqueTogether(
            name='protocolinterface',
            unique_together=set([('protocol_version', 'term')]),
        ),
    ]
