# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-21 14:48
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repocache', '0013_auto_20191120_1457'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='cachedentity',
            name='entity',
        ),
        migrations.AlterUniqueTogether(
            name='cachedentitytag',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='cachedentitytag',
            name='entity',
        ),
        migrations.RemoveField(
            model_name='cachedentitytag',
            name='version',
        ),
        migrations.AlterUniqueTogether(
            name='cachedentityversion',
            unique_together=set([]),
        ),
        migrations.RemoveField(
            model_name='cachedentityversion',
            name='entity',
        ),
        migrations.AlterField(
            model_name='cachedmodel',
            name='entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cachedmodel', to='entities.ModelEntity'),
        ),
        migrations.AlterField(
            model_name='cachedprotocol',
            name='entity',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cachedprotocol', to='entities.ProtocolEntity'),
        ),
        migrations.DeleteModel(
            name='CachedEntity',
        ),
        migrations.DeleteModel(
            name='CachedEntityTag',
        ),
        migrations.DeleteModel(
            name='CachedEntityVersion',
        ),
    ]
