# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-28 13:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repocache', '0014_auto_20191121_1448'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedmodelversion',
            name='message',
            field=models.TextField(default=' ', help_text='Git commit message'),
        ),
        migrations.AddField(
            model_name='cachedprotocolversion',
            name='message',
            field=models.TextField(default=' ', help_text='Git commit message'),
        ),
        migrations.AlterField(
            model_name='cachedmodelversion',
            name='timestamp',
            field=models.DateTimeField(help_text='When this commit was made'),
        ),
        migrations.AlterField(
            model_name='cachedprotocolversion',
            name='timestamp',
            field=models.DateTimeField(help_text='When this commit was made'),
        ),
    ]
