# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-12-04 14:27
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('fitting', '0001_initial'),
        ('repocache', '0014_auto_20191121_1448'),
    ]

    operations = [
        migrations.CreateModel(
            name='CachedFittingSpec',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='cachedfittingspec', to='fitting.FittingSpec')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CachedFittingSpecTag',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('tag', models.CharField(max_length=255)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='repocache.CachedFittingSpec')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='CachedFittingSpecVersion',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('moderated', 'Moderated')], help_text='Public = anyone can view<br />Private = only you can view', max_length=16)),
                ('sha', models.CharField(max_length=40)),
                ('timestamp', models.DateTimeField()),
                ('parsed_ok', models.BooleanField(default=False, help_text='Whether this entity version has been verified as syntactically correct')),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='versions', to='repocache.CachedFittingSpec')),
            ],
            options={
                'ordering': ['-timestamp', '-pk'],
                'get_latest_by': 'timestamp',
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='cachedfittingspectag',
            name='version',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='tags', to='repocache.CachedFittingSpecVersion'),
        ),
        migrations.AlterUniqueTogether(
            name='cachedfittingspecversion',
            unique_together=set([('entity', 'sha')]),
        ),
        migrations.AlterUniqueTogether(
            name='cachedfittingspectag',
            unique_together=set([('entity', 'tag')]),
        ),
    ]
