# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-13 11:29
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repocache', '0015_auto_20191128_1331'),
        ('repocache', '0015_auto_20191204_1427'),
    ]

    operations = [
    ]
