# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-15 10:11
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repocache', '0016_auto_20200107_1710'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cachedmodelversion',
            name='master_filename',
            field=models.TextField(default=None, help_text='Master filename', null=True),
        ),
        migrations.AlterField(
            model_name='cachedprotocolversion',
            name='master_filename',
            field=models.TextField(default=None, help_text='Master filename', null=True),
        ),
    ]
