# -*- coding: utf-8 -*-
# Generated by Django 1.11.23 on 2020-01-15 15:33
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repocache', '0018_auto_20200115_1045'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedmodelversion',
            name='numfiles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='cachedprotocolversion',
            name='numfiles',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
