# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-16 09:13
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('repocache', '0019_auto_20200115_1533'),
        ('repocache', '0015_auto_20191204_1427'),
    ]

    operations = [
    ]
