# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2020-01-16 09:13
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repocache', '0020_merge_20200116_0913'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedfittingspecversion',
            name='author',
            field=models.TextField(default=' ', help_text='Author full name'),
        ),
        migrations.AddField(
            model_name='cachedfittingspecversion',
            name='master_filename',
            field=models.TextField(default=None, help_text='Master filename', null=True),
        ),
        migrations.AddField(
            model_name='cachedfittingspecversion',
            name='message',
            field=models.TextField(default=' ', help_text='Git commit message'),
        ),
        migrations.AddField(
            model_name='cachedfittingspecversion',
            name='numfiles',
            field=models.IntegerField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name='cachedfittingspecversion',
            name='timestamp',
            field=models.DateTimeField(help_text='When this commit was made'),
        ),
    ]
