# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-09-17 13:35
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('repocache', '0021_auto_20200116_0913'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProtocolIoputs',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(help_text='name of the input or output', max_length=200)),
                ('units', models.CharField(blank=True, help_text='units of the input or output, as a pint definition string', max_length=200)),
                ('kind', models.IntegerField(choices=[(1, 'input'), (2, 'output'), (3, 'flag')], help_text='indicates whether this is an input or output variable')),
                ('protocol_version', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='ioputs', to='repocache.CachedProtocolVersion')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='protocolioputs',
            unique_together=set([('protocol_version', 'name', 'kind')]),
        ),
    ]
