# -*- coding: utf-8 -*-
# Generated by Django 1.11.28 on 2020-10-01 13:58
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('repocache', '0022_auto_20200917_1335'),
    ]

    operations = [
        migrations.AddField(
            model_name='cachedfittingspecversion',
            name='has_readme',
            field=models.BooleanField(default=False, help_text='Whether this entity version has a README file'),
        ),
        migrations.AddField(
            model_name='cachedmodelversion',
            name='has_readme',
            field=models.BooleanField(default=False, help_text='Whether this entity version has a README file'),
        ),
        migrations.AddField(
            model_name='cachedprotocolversion',
            name='has_readme',
            field=models.BooleanField(default=False, help_text='Whether this entity version has a README file'),
        ),
    ]
