language: python
cache: pip
python:
  - "3.4"
  - "3.5"
  - "3.6"
services:
  postgresql
env:
  DATABASE_URL=postgres://postgres:@localhost:5432/weblab
before_script:
  - psql -c 'create database weblab;' -U postgres
install:
  pip install -r requirements/test.txt
script:
  pytest weblab
