# -*- coding: utf-8 -*-
# Generated by Django 1.11.20 on 2019-11-28 16:01
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('entities', '0015_auto_20191128_1601'),
    ]

    operations = [
        migrations.CreateModel(
            name='FittingSpec',
            fields=[
                ('entity_ptr', models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='entities.Entity')),
                ('protocol', models.ForeignKey(help_text='the experimental scenario used to fit models', on_delete=django.db.models.deletion.CASCADE, related_name='fitting_specs', to='entities.ProtocolEntity')),
            ],
            options={
                'verbose_name': 'fitting specification',
            },
            bases=('entities.entity',),
        ),
    ]
