# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-08-22 08:42
from __future__ import unicode_literals

import accounts.models
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receive_emails',
            field=models.BooleanField(default=False, help_text='Inform me about finished experiments'),
        ),
        migrations.AlterField(
            model_name='user',
            name='username',
            field=models.CharField(error_messages={'unique': 'A user with that username already exists.'}, max_length=255, unique=True, validators=[accounts.models.UsernameValidator()]),
        ),
    ]
