# Generated by Django 2.2.28 on 2022-09-14 09:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='receive_story_emails',
            field=models.BooleanField(default=True, help_text='User wants to receive emails about changes affecting theri stories'),
        ),
        migrations.AlterField(
            model_name='user',
            name='receive_emails',
            field=models.BooleanField(default=False, help_text='User wants to receive emails about finished experiments'),
        ),
    ]
