# Generated by Django 2.2.24 on 2022-01-25 14:59

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0001_squashed_0034_auto_20211029_0836'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storygraph',
            name='storyitem_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stories.StoryItem'),
        ),
        migrations.AlterField(
            model_name='storytext',
            name='storyitem_ptr',
            field=models.OneToOneField(auto_created=True, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stories.StoryItem'),
        ),
    ]
