# Generated by Django 2.2.16 on 2021-09-07 13:53

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0002_story_experiments'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryText',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text', models.TextField()),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storytexts', to='stories.Story')),
            ],
        ),
    ]
