# Generated by Django 2.2.27 on 2022-03-25 17:53

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0003_auto_20220325_1729'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storygraph',
            name='graphfilename',
            field=models.TextField(blank=True, null=True),
        ),
    ]
