# Generated by Django 2.2.27 on 2022-05-19 16:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_auto_20220325_1753'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storygraph',
            name='modelgroup',
        ),
    ]
