# Generated by Django 2.2.16 on 2021-09-07 17:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0004_auto_20210907_1553'),
    ]

    operations = [
        migrations.DeleteModel(
            name='FamilyMember',
        ),
        migrations.DeleteModel(
            name='Profile',
        ),
    ]
