# Generated by Django 2.2.27 on 2022-05-19 16:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0021_auto_20220316_2004'),
        ('stories', '0005_remove_storygraph_modelgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='storygraph',
            name='grouptoggles',
            field=models.ManyToManyField(blank=True, related_name='toggle_group_story_graphs', to='entities.ModelGroup'),
        ),
        migrations.AddField(
            model_name='storygraph',
            name='modelgroups',
            field=models.ManyToManyField(blank=True, related_name='selected_group_story_graphs', to='entities.ModelGroup'),
        ),
    ]
