# Generated by Django 2.2.27 on 2022-05-31 10:40

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0021_auto_20220316_2004'),
        ('stories', '0006_auto_20220519_1657'),
    ]

    operations = [
        migrations.AddField(
            model_name='storygraph',
            name='models',
            field=models.ManyToManyField(blank=True, related_name='selected_group_story_models', to='entities.ModelEntity'),
        ),
        migrations.AlterField(
            model_name='storygraph',
            name='cachedmodelversions',
            field=models.ManyToManyField(blank=True, related_name='selected_group_story_modelversions', to='repocache.CachedModelVersion'),
        ),
    ]
