# Generated by Django 2.2.16 on 2021-09-08 13:48

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0006_simplestory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='simplestory',
            name='description',
        ),
    ]
