# Generated by Django 2.2.16 on 2021-09-15 10:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_remove_simplestory_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='StoryPart',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('description', models.TextField(blank=True, default='')),
                ('recipe', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storyparts', to='stories.SimpleStory')),
            ],
        ),
    ]
