# Generated by Django 2.2.28 on 2022-09-12 13:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0007_auto_20220531_1040'),
    ]

    operations = [
        migrations.AddField(
            model_name='storygraph',
            name='protocol_is_latest',
            field=models.BooleanField(default=True),
        ),
    ]
