# Generated by Django 2.2.28 on 2022-09-12 14:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0008_storygraph_protocol_is_latest'),
    ]

    operations = [
        migrations.AddField(
            model_name='storygraph',
            name='all_model_versionss_latest',
            field=models.BooleanField(default=True),
        ),
    ]
