# Generated by Django 2.2.16 on 2021-09-16 15:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_auto_20210915_1105'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storypart',
            old_name='recipe',
            new_name='story',
        ),
        migrations.AddField(
            model_name='storypart',
            name='order',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
