# Generated by Django 2.2.28 on 2022-09-12 15:06

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0009_storygraph_all_model_versionss_latest'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storygraph',
            old_name='all_model_versionss_latest',
            new_name='all_model_versions_latest',
        ),
    ]
