# Generated by Django 2.2.28 on 2022-09-14 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_auto_20220912_1506'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='email_sent',
            field=models.BooleanField(default=False),
        ),
    ]
