# Generated by Django 2.2.16 on 2021-09-16 16:17

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0010_auto_20210916_1549'),
    ]

    operations = [
        migrations.AlterOrderWithRespectTo(
            name='storypart',
            order_with_respect_to='story',
        ),
        migrations.RemoveField(
            model_name='storypart',
            name='order',
        ),
    ]
