# Generated by Django 2.2.28 on 2022-09-14 13:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0011_story_email_sent'),
    ]

    operations = [
        migrations.AddField(
            model_name='storygraph',
            name='email_sent',
            field=models.BooleanField(default=True),
        ),
    ]
