# Generated by Django 2.2.16 on 2021-09-22 15:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0012_auto_20210916_1624'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storypart',
            name='story',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storyparts', to='stories.Story'),
        ),
    ]
