# Generated by Django 2.2.16 on 2021-09-22 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0013_auto_20210922_1513'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='experiments',
        ),
        migrations.RemoveField(
            model_name='story',
            name='modelgroups',
        ),
        migrations.RemoveField(
            model_name='story',
            name='othermodels',
        ),
    ]
