# Generated by Django 2.2.16 on 2021-09-22 15:14

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0014_auto_20210922_1514'),
    ]

    operations = [
        migrations.DeleteModel(
            name='SimpleStory',
        ),
    ]
