# Generated by Django 2.2.16 on 2021-09-22 15:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0015_delete_simplestory'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='story',
            name='description',
        ),
    ]
