# Generated by Django 2.2.16 on 2021-10-01 16:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repocache', '0024_auto_20210707_1504'),
        ('stories', '0016_remove_story_description'),
    ]

    operations = [
        migrations.CreateModel(
            name='Graph',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('graphfilename', models.TextField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('cachedmodelversion', models.ManyToManyField(to='repocache.CachedModelVersion')),
                ('cachedprotocolversion', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='protocolforgraph', to='repocache.CachedProtocolVersion')),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storygraphs', to='stories.Story')),
            ],
            options={
                'abstract': False,
            },
        ),
    ]
