# Generated by Django 2.2.16 on 2021-10-01 16:35

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('stories', '0018_graph_order'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storypart',
            name='author',
        ),
        migrations.RemoveField(
            model_name='storypart',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='storypart',
            name='id',
        ),
        migrations.RemoveField(
            model_name='storypart',
            name='order',
        ),
        migrations.RemoveField(
            model_name='storypart',
            name='story',
        ),
        migrations.CreateModel(
            name='StoryItem',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('order', models.IntegerField()),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('story', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='storyparts', to='stories.Story')),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='storypart',
            name='storyitem_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stories.StoryItem'),
            preserve_default=False,
        ),
    ]
