# Generated by Django 2.2.16 on 2021-10-01 16:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0019_auto_20211001_1635'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='graph',
            name='author',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='created_at',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='id',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='order',
        ),
        migrations.RemoveField(
            model_name='graph',
            name='story',
        ),
        migrations.AddField(
            model_name='graph',
            name='storyitem_ptr',
            field=models.OneToOneField(auto_created=True, default=0, on_delete=django.db.models.deletion.CASCADE, parent_link=True, primary_key=True, serialize=False, to='stories.StoryItem'),
            preserve_default=False,
        ),
    ]
