# Generated by Django 2.2.16 on 2021-10-01 16:41

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('repocache', '0024_auto_20210707_1504'),
        ('stories', '0020_auto_20211001_1636'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Graph',
            new_name='StoryGraph',
        ),
        migrations.RenameModel(
            old_name='StoryPart',
            new_name='StoryText',
        ),
    ]
