# Generated by Django 2.2.16 on 2021-10-07 14:16

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0021_auto_20211001_1641'),
    ]

    operations = [
        migrations.RenameField(
            model_name='storygraph',
            old_name='cachedmodelversion',
            new_name='cachedmodelversions',
        ),
    ]
