# Generated by Django 2.2.16 on 2021-10-08 15:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0035_delete_story'),
        ('stories', '0022_auto_20211007_1416'),
    ]

    operations = [
        migrations.AddField(
            model_name='storygraph',
            name='modelgroup',
            field=models.ManyToManyField(blank=True, default=None, to='entities.ModelGroup'),
        ),
    ]
