# Generated by Django 2.2.16 on 2021-10-08 17:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0035_delete_story'),
        ('stories', '0024_remove_storygraph_modelgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='storygraph',
            name='modelgroup',
            field=models.ManyToManyField(blank=True, default='', to='entities.ModelGroup'),
        ),
    ]
