# Generated by Django 2.2.16 on 2021-10-08 17:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0026_auto_20211008_1714'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='storygraph',
            name='modelgroup',
        ),
    ]
