# Generated by Django 2.2.16 on 2021-10-08 17:25

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0035_delete_story'),
        ('stories', '0027_remove_storygraph_modelgroup'),
    ]

    operations = [
        migrations.AddField(
            model_name='storygraph',
            name='modelgroup',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.SET_DEFAULT, to='entities.ModelGroup'),
        ),
    ]
