# Generated by Django 2.2.16 on 2021-10-08 17:30

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0028_storygraph_modelgroup'),
    ]

    operations = [
        migrations.AlterField(
            model_name='storygraph',
            name='modelgroup',
            field=models.ForeignKey(blank=True, default=None, null=True, on_delete=django.db.models.deletion.SET_DEFAULT, to='entities.ModelGroup'),
        ),
    ]
