# Generated by Django 2.2.16 on 2021-10-28 09:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('stories', '0032_auto_20211028_0913'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='graphvisualizer',
            field=models.CharField(choices=[('displayPlotFlot', 'displayPlotFlot'), ('displayPlotHC', 'displayPlotHC')], default='displayPlotFlot', help_text='The different visualisers determine how graphs are shown in this story.', max_length=16),
        ),
    ]
