# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-16 14:40
from __future__ import unicode_literals

from django.conf import settings
import django.core.validators
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Entity',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('entity_type', models.CharField(choices=[('model', 'model'), ('protocol', 'protocol')], max_length=16)),
                ('name', models.CharField(max_length=255, validators=[django.core.validators.MinLengthValidator(2)])),
                ('creation_date', models.DateTimeField(auto_now_add=True)),
                ('visibility', models.CharField(choices=[('private', 'Private'), ('restricted', 'Restricted'), ('public', 'Public')], help_text='Public = anyone can view<br>Restricted = logged in users can view<br>Private = only you can view', max_length=16)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Model entities',
            },
        ),
        migrations.CreateModel(
            name='EntityUpload',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='uploads')),
                ('original_name', models.CharField(max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='ModelEntity',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('entities.entity',),
        ),
        migrations.CreateModel(
            name='ProtocolEntity',
            fields=[
            ],
            options={
                'proxy': True,
                'indexes': [],
            },
            bases=('entities.entity',),
        ),
        migrations.AddField(
            model_name='entityupload',
            name='entity',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='entities.ModelEntity'),
        ),
    ]
