# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 09:36
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0001_initial'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={},
        ),
        migrations.AlterModelOptions(
            name='modelentity',
            options={'verbose_name_plural': 'Model entities'},
        ),
        migrations.AlterModelOptions(
            name='protocolentity',
            options={'verbose_name_plural': 'Protocol entities'},
        ),
    ]
