# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 12:20
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0002_auto_20171019_0936'),
    ]

    operations = [
        migrations.CreateModel(
            name='EntityFile',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('upload', models.FileField(upload_to='uploads')),
                ('original_name', models.CharField(max_length=255)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='files', to='entities.Entity')),
            ],
        ),
        migrations.RemoveField(
            model_name='entityupload',
            name='entity',
        ),
        migrations.DeleteModel(
            name='EntityUpload',
        ),
    ]
