# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 11:59
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0003_auto_20171010_1029'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityupload',
            name='entity',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='entities.ModelEntity'),
            preserve_default=False,
        ),
    ]
