# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-19 13:09
from __future__ import unicode_literals

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entities', '0003_auto_20171019_1220'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='entity',
            unique_together=set([('entity_type', 'name', 'author')]),
        ),
    ]
