# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-23 16:08
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_auto_20171019_1309'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'permissions': (('create_model', 'Can create models'), ('create_protocol', 'Can create protocols'), ('create_model_version', 'Can create new versions of a model'), ('create_protocol_version', 'Can create new versions of a protocol'))},
        ),
    ]
