# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2017-10-10 12:28
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0004_entityupload_entity'),
    ]

    operations = [
        migrations.AddField(
            model_name='entityupload',
            name='original_name',
            field=models.CharField(default='', max_length=255),
            preserve_default=False,
        ),
    ]
