# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-13 12:37
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0005_auto_20171023_1608'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['name'], 'permissions': (('create_model', 'Can create models'), ('create_protocol', 'Can create protocols'), ('create_model_version', 'Can create new versions of a model'), ('create_protocol_version', 'Can create new versions of a protocol'))},
        ),
    ]
