# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-01-26 08:37
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0006_auto_20180113_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='entity',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('restricted', 'Restricted'), ('public', 'Public')], help_text='Public = anyone can view<br />Restricted = logged in users can view<br />Private = only you can view', max_length=16),
        ),
    ]
