# -*- coding: utf-8 -*-
# Generated by Django 1.11.4 on 2018-05-10 08:24
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0007_auto_20180126_0837'),
    ]

    operations = [
        migrations.RenameField(
            model_name='entity',
            old_name='creation_date',
            new_name='created_at',
        ),
    ]
