# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-06-20 15:44
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0008_auto_20180510_0824'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='git_remote_url',
            field=models.URLField(blank=True, help_text='Git remote to clone from'),
        ),
    ]
