# -*- coding: utf-8 -*-
# Generated by Django 1.11.13 on 2018-09-06 11:50
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0008_auto_20180510_0824'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='visibility',
        ),
    ]
