# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2018-11-29 16:45
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0010_auto_20181129_1327'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['name'], 'permissions': (('create_model', 'Can create models'), ('create_protocol', 'Can create protocols'), ('edit_entity', 'Can edit entity'))},
        ),
    ]
