# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-01-11 17:05
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import uuid


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0011_auto_20181129_1645'),
    ]

    operations = [
        migrations.CreateModel(
            name='AnalysisTask',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('version', models.CharField(max_length=40)),
                ('entity', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='analysis_tasks', to='entities.Entity')),
            ],
        ),
        migrations.AlterUniqueTogether(
            name='analysistask',
            unique_together=set([('entity', 'version')]),
        ),
    ]
