# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-04-08 13:54
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0012_auto_20190111_1705'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['name'], 'permissions': (('create_model', 'Can create models'), ('create_protocol', 'Can create protocols'), ('edit_entity', 'Can edit entity'), ('moderator', 'Can promote public entity versions to moderated'))},
        ),
    ]
