# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-30 13:02
from __future__ import unicode_literals

from django.db import migrations, models


def set_initial_fitting_specs(apps, schema_editor):
    Entity = apps.get_model('entities', 'Entity')
    Entity.objects.update(is_fitting_spec=models.Q(name__startswith='Fit '))


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0013_auto_20190408_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='is_fitting_spec',
            field=models.BooleanField(
                default=False,
                help_text='This protocol is a parameter fitting specification'),
        ),
        migrations.RunPython(set_initial_fitting_specs, migrations.RunPython.noop),
    ]
