# -*- coding: utf-8 -*-
# Generated by Django 1.11.15 on 2019-05-30 13:02
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0013_auto_20190408_1354'),
    ]

    operations = [
        migrations.AddField(
            model_name='entity',
            name='is_fitting_spec',
            field=models.BooleanField(
                default=models.Q(name__startswith='Fit '),
                help_text='This protocol is a parameter fitting specification'),
        ),
        migrations.AlterField(
            model_name='entity',
            name='is_fitting_spec',
            field=models.BooleanField(default=False, help_text='This protocol is a parameter fitting specification'),
        ),
    ]
