# Generated by Django 2.2.16 on 2020-11-25 15:02

from django.db import migrations

def delete_protocols(apps, schema_editor):

    Protocol = apps.get_model('entities', 'ProtocolEntity')
    for protocol in Protocol.objects.all():
        if protocol.is_fitting_spec:
            protocol.delete();


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0015_auto_20191128_1601'),
    ]

    operations = [
        migrations.RunPython(delete_protocols),
    ]
