# Generated by Django 2.2.16 on 2020-11-25 15:28

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0016_delete_old_style_fitting_specs'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='entity',
            name='is_fitting_spec',
        ),
    ]
