# Generated by Django 2.2.16 on 2020-12-01 11:15

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0017_remove_entity_is_fitting_spec'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='entity',
            options={'ordering': ['name'], 'permissions': (('create_model', 'Can create models'), ('create_protocol', 'Can create protocols'), ('create_fittingspec', 'Can create fitting specifications'), ('moderator', 'Can promote public entity versions to moderated'), ('edit_entity', 'Can edit entity'))},
        ),
    ]
