# Generated by Django 2.2.16 on 2021-07-07 15:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0018_auto_20201201_1115'),
    ]

    operations = [
        migrations.CreateModel(
            name='ModelGroup',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100)),
                ('models', models.ManyToManyField(to='entities.ModelEntity')),
            ],
            options={
                'ordering': ['title'],
                'unique_together': {('title',)},
            },
        ),
    ]
