# Generated by Django 2.2.24 on 2022-01-25 14:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0019_modelgroup_squashed_0035_delete_story'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelgroup',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL),
        ),
        migrations.AlterField(
            model_name='modelgroup',
            name='created_at',
            field=models.DateTimeField(auto_now_add=True),
        ),
        migrations.AlterField(
            model_name='modelgroup',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('moderated', 'Moderated')], help_text='Moderated = public and checked by a moderator<br />Public = anyone can view<br />Private = only you can view', max_length=16),
        ),
    ]
