# Generated by Django 2.2.24 on 2022-03-16 20:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0020_auto_20220125_1459'),
    ]

    operations = [
        migrations.AlterField(
            model_name='modelgroup',
            name='models',
            field=models.ManyToManyField(related_name='model_groups', to='entities.ModelEntity'),
        ),
    ]
