# Generated by Django 2.2.16 on 2021-07-13 14:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0020_auto_20210708_1240'),
    ]

    operations = [
        migrations.AddField(
            model_name='modelgroup',
            name='visibility',
            field=models.CharField(choices=[('private', 'Private'), ('public', 'Public'), ('moderated', 'Moderated')], default='Private', help_text='Moderated = public and checked by a moderator<br />Public = anyone can view<br />Private = only you can view', max_length=16),
            preserve_default=False,
        ),
    ]
