# Generated by Django 2.2.16 on 2021-07-13 15:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0021_modelgroup_visibility'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelgroup',
            options={'ordering': ['visibility', 'title']},
        ),
        migrations.AlterField(
            model_name='modelgroup',
            name='title',
            field=models.CharField(max_length=255),
        ),
    ]
