# Generated by Django 2.2.16 on 2021-07-13 15:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0022_auto_20210713_1530'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelgroup',
            options={'ordering': ['title']},
        ),
    ]
