# Generated by Django 2.2.16 on 2021-07-14 12:45

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0023_auto_20210713_1541'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelgroup',
            options={'ordering': ['title'], 'permissions': (('edit_modelgroup', 'Can edit modelgroup'),)},
        ),
    ]
