# Generated by Django 2.2.16 on 2021-07-16 09:40

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0025_auto_20210714_1346'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelgroup',
            options={'ordering': ['title'], 'permissions': (('edit_modelgroup', 'Can edit modelgroup'),)},
        ),
    ]
