# Generated by Django 2.2.16 on 2021-07-16 10:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0026_auto_20210716_0940'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='modelgroup',
            options={'ordering': ['title'], 'permissions': (('edit_entity', 'Can edit modelgroup'),)},
        ),
    ]
