# Generated by Django 2.2.16 on 2021-07-21 09:30

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('entities', '0028_auto_20210716_1003'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='modelgroup',
            unique_together={('title', 'author')},
        ),
    ]
