# Generated by Django 2.2.16 on 2021-08-24 13:28

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0030_story'),
    ]

    operations = [
        migrations.AddField(
            model_name='story',
            name='models',
            field=models.ManyToManyField(to='entities.ModelEntity'),
        ),
    ]
