# Generated by Django 2.2.16 on 2021-08-24 13:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0031_story_models'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='models',
            new_name='othermodels',
        ),
        migrations.AddField(
            model_name='story',
            name='modelgroupss',
            field=models.ManyToManyField(to='entities.ModelGroup'),
        ),
    ]
