# Generated by Django 2.2.16 on 2021-08-24 13:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0032_auto_20210824_1329'),
    ]

    operations = [
        migrations.RenameField(
            model_name='story',
            old_name='modelgroupss',
            new_name='modelgroups',
        ),
    ]
