# Generated by Django 2.2.16 on 2021-08-31 13:32

from django.db import migrations
from django.db import models


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0033_auto_20210824_1330'),
    ]

    operations = [
        migrations.AlterField(
            model_name='story',
            name='description',
            field=models.CharField(),
        ),
    ]
