# Generated by Django 2.2.16 on 2021-09-06 15:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('entities', '0034_auto_20210831_1332'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Story',
        ),
    ]
